FROM quay.io/<account id>/pim:base

COPY fraud_analytics_config.sh /usr/bin/
COPY fraud_analytics_config.service /etc/systemd/system
RUN systemctl unmask fraud_analytics_config.service
RUN systemctl enable fraud_analytics_config.service

COPY fraud-analytics.container /usr/share/containers/systemd


