FROM na.artifactory.swg-devops.com/sys-pcloud-docker-local/devops/pim/base

COPY vllm/llm_config.sh /usr/bin/
COPY utility/download_model.py /usr/bin/
COPY vllm/llm_config.service /etc/systemd/system
RUN systemctl unmask llm_config.service
RUN systemctl enable llm_config.service

COPY vllm/vllm.container /usr/share/containers/systemd
