FROM quay.io/powercloud/pim:base

COPY llm_config.sh /usr/bin/
COPY download_model.py /usr/bin/
COPY llm_config.service /etc/systemd/system
RUN systemctl unmask llm_config.service
RUN systemctl enable llm_config.service

COPY vllm.container /usr/share/containers/systemd
