CREATE SCHEMA PIM ;
  
CREATE TABLE PIM.INDEXED_TR ( 
	"INDEX" INTEGER DEFAULT NULL , 
	USER_ID INTEGER DEFAULT NULL , 
	CARD INTEGER DEFAULT NULL , 
	"YEAR" INTEGER DEFAULT NULL , 
	"MONTH" INTEGER DEFAULT NULL , 
	"DAY" INTEGER DEFAULT NULL , 
	"TIME" CHAR(5) CCSID 37 DEFAULT NULL , 
	AMOUNT VARCHAR(20) CCSID 37 DEFAULT NULL , 
	USE_CHIP VARCHAR(128) CCSID 37 DEFAULT NULL , 
	MERCHANT_NAME FOR COLUMN MERCH00001 VARCHAR(128) CCSID 37 DEFAULT NULL , 
	MERCHANT_CITY FOR COLUMN MERCH00002 VARCHAR(128) CCSID 37 DEFAULT NULL , 
	MERCHANT_STATE FOR COLUMN MERCH00003 VARCHAR(128) CCSID 37 DEFAULT NULL , 
	ZIP DOUBLE PRECISION DEFAULT NULL , 
	MCC INTEGER DEFAULT NULL , 
	IS_ERRORS VARCHAR(128) CCSID 37 DEFAULT NULL , 
	IS_FRAUD VARCHAR(4) CCSID 37 DEFAULT NULL )   
	  
	RCDFMT INDEXED_TR ; 
