FROM quay.io/<account id>/pim:vllm

COPY hmc_config.sh /usr/bin
COPY hmc_config.service /etc/systemd/system
RUN systemctl unmask hmc_config.service
RUN systemctl enable hmc_config.service

COPY hmc_agent.container /usr/share/containers/systemd
COPY hmc_server.container /usr/share/containers/systemd
