FROM registry.stage.redhat.io/rhel9/rhel-bootc:9.6

RUN dnf -y install cloud-init && \
    ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}
COPY usr/ /usr/

COPY get_pimconfig.sh /usr/bin/
COPY pimconfig.service /etc/systemd/system

RUN systemctl unmask pimconfig.service
RUN systemctl enable pimconfig.service

COPY vllm.container /usr/share/containers/systemd
